[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jellyash"
dynamic = ["version"]
license = {file = "LICENSE"}
dependencies = [
	"jellyfin_apiclient_python",
]

[project.scripts]
create_jellyfin_token = "jellyash.token:create_jellyfin_token"
nextup = "jellyash.nextup:nextup"

[tool.setuptools.dynamic]
version = {attr = "jellyash.__version__"}
